# Generated by Django 5.2.7 on 2025-11-02 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='busroute',
            unique_together=set(),
        ),
    ]
