# Generated by Django 5.1.1 on 2025-10-29 05:25

import maps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.FloatField(blank=True, null=True, validators=[maps.models.check_legit_latitude]),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.FloatField(blank=True, null=True, validators=[maps.models.check_legit_longitude]),
        ),
    ]
