# Generated by Django 5.2.7 on 2025-11-02 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_alter_busroute_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='end_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes_ending', to='maps.busstation'),
        ),
        migrations.AddField(
            model_name='busroute',
            name='start_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes_starting', to='maps.busstation'),
        ),
    ]
