# Generated by Django 5.2.7 on 2025-11-02 11:25

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_busroute_end_station_busroute_start_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busroute',
            name='geom',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
    ]
